-- MySQL Script generated by MySQL Workbench
-- Wed Mar  8 15:38:25 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema madera
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `madera` ;

-- -----------------------------------------------------
-- Schema madera
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `madera` DEFAULT CHARACTER SET utf8 ;
USE `madera` ;

-- -----------------------------------------------------
-- Table `madera`.`Groupe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madera`.`Groupe` ;

CREATE TABLE IF NOT EXISTS `madera`.`Groupe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madera`.`Pays`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madera`.`Pays` ;

CREATE TABLE IF NOT EXISTS `madera`.`Pays` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madera`.`City`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madera`.`Ville` ;

CREATE TABLE IF NOT EXISTS `madera`.`Ville` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `Pays_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Ville_Pays1_idx` (`Pays_id` ASC),
  CONSTRAINT `fk_Ville_Pays1`
    FOREIGN KEY (`Pays_id`)
    REFERENCES `madera`.`Pays` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madera`.`Site`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madera`.`Site` ;

CREATE TABLE IF NOT EXISTS `madera`.`Site` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `Ville_id` INT NOT NULL,
  `CP` VARCHAR(5) NOT NULL,
  `adresse` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Site_Ville1_idx` (`Ville_id` ASC),
  CONSTRAINT `fk_Site_Ville1`
    FOREIGN KEY (`Ville_id`)
    REFERENCES `madera`.`Ville` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madera`.`Utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madera`.`Utilisateur` ;

CREATE TABLE IF NOT EXISTS `madera`.`Utilisateur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `numeroTel` VARCHAR(13) NULL,
  `mail` VARCHAR(45) NULL,
  `Groupe_id` INT NOT NULL,
  `Site_id` INT NOT NULL,
  `mpd` VARCHAR(255) NULL,
  `token` VARCHAR(255) NULL,
  `token_expir` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Utilisateur_Groupe_idx` (`Groupe_id` ASC),
  INDEX `fk_Utilisateur_Site1_idx` (`Site_id` ASC),
  CONSTRAINT `fk_Utilisateur_Groupe`
    FOREIGN KEY (`Groupe_id`)
    REFERENCES `madera`.`Groupe` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Utilisateur_Site1`
    FOREIGN KEY (`Site_id`)
    REFERENCES `madera`.`Site` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madera`.`Projet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madera`.`Projet` ;

CREATE TABLE IF NOT EXISTS `madera`.`Projet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dateCrea` TIMESTAMP NOT NULL,
  `nom` VARCHAR(45) NULL,
  `Utilisateur_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_projet_Utilisateur1_idx` (`Utilisateur_id` ASC),
  CONSTRAINT `fk_projet_Utilisateur1`
    FOREIGN KEY (`Utilisateur_id`)
    REFERENCES `madera`.`Utilisateur` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madera`.`Etat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madera`.`Etat` ;

CREATE TABLE IF NOT EXISTS `madera`.`Etat` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madera`.`Devis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madera`.`Devis` ;

CREATE TABLE IF NOT EXISTS `madera`.`Devis` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Projet_id` INT NOT NULL,
  `dateDebut` DATE NOT NULL,
  `dateFin` DATE NULL,
  `idCommercial` INT NOT NULL,
  `Etat_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Devis_Projet1_idx` (`Projet_id` ASC),
  INDEX `fk_Devis_Utilisateur1_idx` (`idCommercial` ASC),
  INDEX `fk_Devis_Etat1_idx` (`Etat_id` ASC),
  CONSTRAINT `fk_Devis_Projet1`
    FOREIGN KEY (`Projet_id`)
    REFERENCES `madera`.`Projet` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Devis_Utilisateur1`
    FOREIGN KEY (`idCommercial`)
    REFERENCES `madera`.`Utilisateur` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Devis_Etat1`
    FOREIGN KEY (`Etat_id`)
    REFERENCES `madera`.`Etat` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madera`.`Module`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madera`.`Module` ;

CREATE TABLE IF NOT EXISTS `madera`.`Module` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `coupe_principale` VARCHAR(45) NOT NULL,
  `cctp` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madera`.`famille de composant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madera`.`famille de composant` ;

CREATE TABLE IF NOT EXISTS `madera`.`famille de composant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madera`.`Param_calcul`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madera`.`Param_calcul` ;

CREATE TABLE IF NOT EXISTS `madera`.`Param_calcul` (
  `id` INT NOT NULL,
  `prix` FLOAT NULL,
  `prix_vente` FLOAT NULL,
  `marge_commerciaux` FLOAT NULL,
  `marge_entreprise` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madera`.`Modele_gamme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madera`.`Modele_gamme` ;

CREATE TABLE IF NOT EXISTS `madera`.`Modele_gamme` (
  `idModele_gamme` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idModele_gamme`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madera`.`Gammes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madera`.`Gammes` ;

CREATE TABLE IF NOT EXISTS `madera`.`Gammes` (
  `id` INT NOT NULL,
  `finition_extern` VARCHAR(45) NULL,
  `isolant_type` VARCHAR(45) NULL,
  `couverture_type` VARCHAR(45) NULL,
  `gammescol` VARCHAR(45) NULL,
  `param_calcul_id` INT NOT NULL,
  `Modele_gamme_idModele_gamme` INT NOT NULL,
  PRIMARY KEY (`id`, `param_calcul_id`),
  INDEX `fk_gammes_param_calcul1_idx` (`param_calcul_id` ASC),
  INDEX `fk_Gammes_Modele_gamme1_idx` (`Modele_gamme_idModele_gamme` ASC),
  CONSTRAINT `fk_gammes_param_calcul1`
    FOREIGN KEY (`param_calcul_id`)
    REFERENCES `madera`.`Param_calcul` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Gammes_Modele_gamme1`
    FOREIGN KEY (`Modele_gamme_idModele_gamme`)
    REFERENCES `madera`.`Modele_gamme` (`idModele_gamme`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madera`.`Composant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madera`.`Composant` ;

CREATE TABLE IF NOT EXISTS `madera`.`Composant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `famille_composant_id` INT NOT NULL,
  `nature` VARCHAR(45) NULL,
  `caractéristique` VARCHAR(45) NULL,
  `unite_usage` VARCHAR(45) NULL,
  `Gammes_id` INT NOT NULL,
  `Gammes_param_calcul_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Piece_Materiau1_idx` (`famille_composant_id` ASC),
  INDEX `fk_Composant_Gammes1_idx` (`Gammes_id` ASC, `Gammes_param_calcul_id` ASC),
  CONSTRAINT `fk_Piece_Materiau1`
    FOREIGN KEY (`famille_composant_id`)
    REFERENCES `madera`.`famille de composant` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Composant_Gammes1`
    FOREIGN KEY (`Gammes_id` , `Gammes_param_calcul_id`)
    REFERENCES `madera`.`Gammes` (`id` , `param_calcul_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madera`.`Module_has_composants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madera`.`Module_has_composants` ;

CREATE TABLE IF NOT EXISTS `madera`.`Module_has_composants` (
  `Module_id` INT NOT NULL,
  `composant_id` INT NOT NULL,
  PRIMARY KEY (`Module_id`, `composant_id`),
  INDEX `fk_Module_has_composant_composant1_idx` (`composant_id` ASC),
  INDEX `fk_Module_has_composant_Module1_idx` (`Module_id` ASC),
  CONSTRAINT `fk_Module_has_composant_Module1`
    FOREIGN KEY (`Module_id`)
    REFERENCES `madera`.`Module` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Module_has_composant_composant1`
    FOREIGN KEY (`composant_id`)
    REFERENCES `madera`.`Composant` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madera`.`Fournisseurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madera`.`Fournisseurs` ;

CREATE TABLE IF NOT EXISTS `madera`.`Fournisseurs` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `Site_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fournisseurs_Site1_idx` (`Site_id` ASC),
  CONSTRAINT `fk_fournisseurs_Site1`
    FOREIGN KEY (`Site_id`)
    REFERENCES `madera`.`Site` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madera`.`mode_conception`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madera`.`mode_conception` ;

CREATE TABLE IF NOT EXISTS `madera`.`mode_conception` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madera`.`Fournisseurs_has_composant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madera`.`Fournisseurs_has_composant` ;

CREATE TABLE IF NOT EXISTS `madera`.`Fournisseurs_has_composant` (
  `fournisseurs_id` INT NOT NULL,
  `composant_id` INT NOT NULL,
  PRIMARY KEY (`fournisseurs_id`, `composant_id`),
  INDEX `fk_fournisseurs_has_composant_composant1_idx` (`composant_id` ASC),
  INDEX `fk_fournisseurs_has_composant_fournisseurs1_idx` (`fournisseurs_id` ASC),
  CONSTRAINT `fk_fournisseurs_has_composant_fournisseurs1`
    FOREIGN KEY (`fournisseurs_id`)
    REFERENCES `madera`.`Fournisseurs` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_fournisseurs_has_composant_composant1`
    FOREIGN KEY (`composant_id`)
    REFERENCES `madera`.`Composant` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madera`.`Mode_conception_has_param_calcul`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madera`.`Mode_conception_has_param_calcul` ;

CREATE TABLE IF NOT EXISTS `madera`.`Mode_conception_has_param_calcul` (
  `mode_conception_id` INT NOT NULL,
  `param_calcul_id` INT NOT NULL,
  PRIMARY KEY (`mode_conception_id`, `param_calcul_id`),
  INDEX `fk_mode_conception_has_param_calcul_param_calcul1_idx` (`param_calcul_id` ASC),
  INDEX `fk_mode_conception_has_param_calcul_mode_conception1_idx` (`mode_conception_id` ASC),
  CONSTRAINT `fk_mode_conception_has_param_calcul_mode_conception1`
    FOREIGN KEY (`mode_conception_id`)
    REFERENCES `madera`.`mode_conception` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_mode_conception_has_param_calcul_param_calcul1`
    FOREIGN KEY (`param_calcul_id`)
    REFERENCES `madera`.`Param_calcul` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madera`.`Devis_has_Module`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madera`.`Devis_has_Module` ;

CREATE TABLE IF NOT EXISTS `madera`.`Devis_has_Module` (
  `Devis_id` INT NOT NULL,
  `Module_id` INT NOT NULL,
  PRIMARY KEY (`Devis_id`, `Module_id`),
  INDEX `fk_Devis_has_Module_Module1_idx` (`Module_id` ASC),
  INDEX `fk_Devis_has_Module_Devis1_idx` (`Devis_id` ASC),
  CONSTRAINT `fk_Devis_has_Module_Devis1`
    FOREIGN KEY (`Devis_id`)
    REFERENCES `madera`.`Devis` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Devis_has_Module_Module1`
    FOREIGN KEY (`Module_id`)
    REFERENCES `madera`.`Module` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
